/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;


import controller.Listagem;
import java.util.Comparator;
import java.util.List;
import java.util.Vector;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import model.Animal;



/**
 *
 * @author paulo
 */
public class JFListagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFListagem
     */
    public JFListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cbTodos = new javax.swing.JCheckBox();
        cbEquinos = new javax.swing.JCheckBox();
        cbSuinos = new javax.swing.JCheckBox();
        cbBovinos = new javax.swing.JCheckBox();
        cbAves = new javax.swing.JCheckBox();
        jbImprimir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbImprimir1 = new javax.swing.JButton();
        jbImprimir2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Listagem de Itens");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        buttonGroup1.add(cbTodos);
        cbTodos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbTodos.setText("Todos");
        cbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTodosActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbEquinos);
        cbEquinos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbEquinos.setText("Equinos");

        buttonGroup1.add(cbSuinos);
        cbSuinos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbSuinos.setText("Suinos");

        buttonGroup1.add(cbBovinos);
        cbBovinos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbBovinos.setText("Bovinos");

        buttonGroup1.add(cbAves);
        cbAves.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbAves.setText("Aves");

        jbImprimir.setText("Excluir");
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Por id");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Raca", "Sexo", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jbImprimir1.setText("Update");
        jbImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimir1ActionPerformed(evt);
            }
        });

        jbImprimir2.setText("Pesquisar");
        jbImprimir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cbTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAves, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEquinos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSuinos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBovinos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbImprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(469, Short.MAX_VALUE)
                    .addComponent(jbImprimir2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTodos)
                    .addComponent(cbEquinos)
                    .addComponent(cbSuinos)
                    .addComponent(cbBovinos)
                    .addComponent(cbAves))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbImprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jbImprimir2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        setBounds(650, 10, 588, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void cbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTodosActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        JFPrincipal.listagem=true;
        cbTodos.setSelected(true);
    }//GEN-LAST:event_formInternalFrameOpened

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed
        // TODO add your handling code here:
        jTable1.removeRowSelectionInterval(WIDTH, WIDTH);
                
        
    }//GEN-LAST:event_jbImprimirActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jbImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbImprimir1ActionPerformed

    private void jbImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimir2ActionPerformed
        // TODO add your handling code here:
        
        EntityManagerFactory fb = Persistence.createEntityManagerFactory("animais");
        EntityManager ger = fb.createEntityManager();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        Listagem item = new Listagem();
      //  DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        // List<Animal> lista = ger.createQuery("from Animal tipo").getResultList();
      //  List<Animal> list = ger.createQuery("from Animal id").getResultList();
           // lista.stream().forEach(i -> modelo.addRow(new Object[]{i.getId(),i.getRaca(),i.getSexo(),i.getTipo()}));
     //   item.setId(Long.parseLong(jLabel1.getText()));
      //  Animal nnn = ger.find(Animal.class, item.getId());
       // modelo.addRow(new Object[]{nnn.getId(), nnn.getRaca(), nnn.getSexo(), nnn.getTipo()});
        if(cbAves.isSelected()){
            item.setAves("Ave");
            List<Animal> list = ger.createQuery("from Animal tipo").getResultList();
            list.stream().filter(a-> a.getTipo().equals("Ave")).forEach(i -> modelo.addRow(new Object[]{i.getId(),i.getRaca(),i.getSexo(),i.getTipo()}));

      
      
        // List<Animal> lista = ger.createQuery("from Animal id").getResultList();
            //list.stream().forEach(i ->  modelo.addColumn(i.getId()));
            
            
        }else if(cbBovinos.isSelected()){
            item.setBovinos("Bovino");
            List<Animal> list = ger.createQuery("from Animal tipo").getResultList();
           list.stream().filter(a-> a.getTipo().equals("Bovino")).forEach(i -> modelo.addRow(new Object[]{i.getId(),i.getRaca(),i.getSexo(),i.getTipo()}));
        }else if(cbEquinos.isSelected()){
            item.setEquinos("Equino");
            List<Animal> list = ger.createQuery("from Animal tipo").getResultList();
              list.stream().filter(a-> a.getTipo().equals("Equino")).forEach(i -> modelo.addRow(new Object[]{i.getId(),i.getRaca(),i.getSexo(),i.getTipo()}));

        }else if(cbSuinos.isSelected()){
            item.setSuinos("Suino");
              List<Animal> list = ger.createQuery("from Animal tipo").getResultList();
              list.stream().filter(a-> a.getTipo().equals("Suino")).forEach(i -> modelo.addRow(new Object[]{i.getId(),i.getRaca(),i.getSexo(),i.getTipo()}));

        }else{
            item.setTodos("Animal");
            List<Animal> list = ger.createQuery("from Animal id").getResultList();
            list.stream().forEach(i -> modelo.addRow(new Object[]{i.getId(),i.getRaca(),i.getSexo(),i.getTipo()}));
          //   list.stream().filter(a-> a.getTipo().equals("Bovino")).forEach(i -> modelo.addRow(new Object[]{i.getId(),i.getRaca(),i.getSexo(),i.getTipo()}));

        }
        

         fb.close();
         ger.close();
         
    }//GEN-LAST:event_jbImprimir2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAves;
    private javax.swing.JCheckBox cbBovinos;
    private javax.swing.JCheckBox cbEquinos;
    private javax.swing.JCheckBox cbSuinos;
    private javax.swing.JCheckBox cbTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbImprimir1;
    private javax.swing.JButton jbImprimir2;
    // End of variables declaration//GEN-END:variables
}
